Feature: add subcommand for merging binaries
esp-rs/espflash pull request #152
Opened 2022-03-28 08:31 UTC by JurajSadel

Feature: add the option for merging bootloader, partition-table and application binary into a single binary.
Closes #79 

Note: To get a chip revision, the connection is needed, for simplicity, the revision None is used.

2022-03-28 09:57 UTC, bjoernQ commented on espflash/src/cli/mod.rs
> +        use std::io::Write;
not sure we use this import style anywhere in this repo? maybe just move it to the top?

2022-03-28 09:58 UTC, bjoernQ commented on espflash/src/cli/mod.rs
> +            let buf =
can we find a better name? like `padding_bytes` or similar?

2022-03-28 09:58 UTC, bjoernQ commented on espflash/src/cli/mod.rs
> +                vec![b'\xFF'; segment.addr as usize - file.metadata().unwrap().len() as usize];
I guess `0xffu8` would be easier to read than `b'\xFF'`

2022-03-28 10:01 UTC, bjoernQ commented
besides some nitpicking it looks good to me - hopefully we don't get merge conflicts with the rather large draft PR addressing support for ESP32C2

2022-03-28 10:20 UTC, MabezDev requested changes

2022-03-28 10:20 UTC, MabezDev commented on espflash/src/cli/mod.rs
> +        let merged_bin = format!("merged_{path}", path = &path.to_str().unwrap());
And this unwrap

2022-03-28 10:20 UTC, MabezDev commented on espflash/src/cli/mod.rs
> +            fs::remove_file(&merged_bin).unwrap();
Ditto

2022-03-28 10:20 UTC, MabezDev commented on espflash/src/cli/mod.rs
> +            .unwrap();
Ditto

2022-03-29 08:08 UTC, JurajSadel commented
Thank you @bjoernQ, @MabezDev for the reviews!

2022-03-29 09:40 UTC, MabezDev approved these changes
LGTM! Haven't actually tested with QEMU, but it looks like it should work fine :)

2022-03-29 09:40 UTC, merged